"""initial tables

Revision ID: 6a2b8e0db995
Revises: 
Create Date: 2026-03-06 04:22:33.010542
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a2b8e0db995'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('request_headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('search_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_log_search', 'api_logs', ['search_id'], unique=False)
    op.create_index('ix_api_log_supplier', 'api_logs', ['supplier_id', 'created_at'], unique=False)
    op.create_table('gateway_bookings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_booking_id', sa.String(length=255), nullable=True),
    sa.Column('laravel_booking_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('vehicle_name', sa.String(length=500), nullable=True),
    sa.Column('pickup_location', sa.String(length=500), nullable=True),
    sa.Column('dropoff_location', sa.String(length=500), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(), nullable=True),
    sa.Column('dropoff_datetime', sa.DateTime(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('driver_email', sa.String(length=255), nullable=True),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_laravel', 'gateway_bookings', ['laravel_booking_id'], unique=False)
    op.create_index('ix_booking_supplier', 'gateway_bookings', ['supplier_id', 'supplier_booking_id'], unique=False)
    op.create_table('provider_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_location_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_norm', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('city_norm', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('country_norm', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('type_norm', sa.String(length=50), nullable=True),
    sa.Column('iata', sa.String(length=10), nullable=True),
    sa.Column('iata_norm', sa.String(length=10), nullable=True),
    sa.Column('geohash', sa.String(length=12), nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_loc_country_city', 'provider_locations', ['provider', 'country_norm', 'city_norm'], unique=False)
    op.create_index('ix_provider_loc_iata', 'provider_locations', ['provider', 'iata_norm'], unique=False)
    op.create_index('ix_provider_loc_unique', 'provider_locations', ['provider', 'provider_location_id'], unique=True)
    op.create_table('unified_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unified_location_id', sa.BigInteger(), nullable=False),
    sa.Column('match_key', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('aliases', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('iata', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('our_location_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_key')
    )
    op.create_index('ix_unified_loc_country_city', 'unified_locations', ['country', 'city'], unique=False)
    op.create_index('ix_unified_loc_iata', 'unified_locations', ['iata'], unique=False)
    op.create_index(op.f('ix_unified_locations_unified_location_id'), 'unified_locations', ['unified_location_id'], unique=True)
    op.create_table('unified_location_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unified_location_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_location_id', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('dropoffs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unified_location_id'], ['unified_locations.unified_location_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mapping_provider_unique', 'unified_location_mappings', ['provider', 'provider_location_id'], unique=True)
    op.create_index('ix_mapping_unified_id', 'unified_location_mappings', ['unified_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mapping_unified_id', table_name='unified_location_mappings')
    op.drop_index('ix_mapping_provider_unique', table_name='unified_location_mappings')
    op.drop_table('unified_location_mappings')
    op.drop_index(op.f('ix_unified_locations_unified_location_id'), table_name='unified_locations')
    op.drop_index('ix_unified_loc_iata', table_name='unified_locations')
    op.drop_index('ix_unified_loc_country_city', table_name='unified_locations')
    op.drop_table('unified_locations')
    op.drop_index('ix_provider_loc_unique', table_name='provider_locations')
    op.drop_index('ix_provider_loc_iata', table_name='provider_locations')
    op.drop_index('ix_provider_loc_country_city', table_name='provider_locations')
    op.drop_table('provider_locations')
    op.drop_index('ix_booking_supplier', table_name='gateway_bookings')
    op.drop_index('ix_booking_laravel', table_name='gateway_bookings')
    op.drop_table('gateway_bookings')
    op.drop_index('ix_api_log_supplier', table_name='api_logs')
    op.drop_index('ix_api_log_search', table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
